require: 
  - rubocop-performance
  - rubocop-rails
  # rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 1000

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false