name: CI

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
    

  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rubocop
