name: CI

on: [push]

jobs:
  # TODO: Fix the database issues
  # test:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: 2.7.1
  #   - name: Install postgres client
  #     run: sudo apt-get install libpq-dev
  #   - name: Install dependencies
  #     run: bundle install
  #   - name: Setup database
  #     env:
  #       RAILS_ENV: test
  #     run: bundle exec rake db:setup
  #   - name: Run tests
  #     run: bundle exec rake
    

  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rubocop
